config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/my_portfolio' => 'users#my_portfolio'
  get '/get_stocks' => 'stocks#search'
  get '/get_friends' => 'users#search'

  get '/create_stock' => 'stocks#create'
  get '/create_friendship' => 'users#add_friend'

  get '/connect' => 'users#connect'

  resources :sessions
  resources :users
  resources :stocks, only: [:destroy]
  resources :friendships, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  # scope :by_ticker, -> (ticker_symbol) { where(ticker: ticker_symbol) }
  belongs_to :user
  def self.new_from_lookup(ticker_symbol)
    look_up = StockQuote::Stock.quote(ticker_symbol)
    return nil unless look_up.name

    new_stock = Stock.new(ticker: look_up.symbol, name: look_up.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol)
  end

  def price
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price}" if closing_price

    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price}" if opening_price

    'Unavailable'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def can_add?(ticker)
    under_stock_limit? && !stock_already_added?(ticker)
  end

  def under_stock_limit?
    if self.stocks.count > 6
      return false
    else
      return true
    end
  end

  def stock_already_added?(ticker)
    if self.stocks.where(ticker: ticker).exists?
      return true
    else
      return false
    end
  end

  def not_friends_with(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def execpt_current_user(user)
    user.reject { |u| u.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!
    (name_matches(param) + email_matches(param))
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to login_path unless current_user
  end

  helper_method :current_user
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendships = current_user.friendships.find_by(friend_id: params[:id])
    @friendships.destroy
    respond_to do |format|
      format.html { redirect_to connect_path, notice: 'Successfully unfriended' }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:notice] = "Error..."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock]
      # @tracker = Stock.find_by_ticker(params[:stock])
      @tracker ||= Stock.new_from_lookup(params[:stock])
      respond_to do |format|
        if @tracker
          format.html { render partial: "lookup" }
          format.json { render json: @tracker }
          # @tracker.save
        else
          format.json { render status: :not_found, nothing: true }
        end
      end
    end
  end

  def create
    if params[:stock].present?
      @stock = current_user.stocks.new(ticker: params[:ticker], name: params[:name], last_price: params[:last_price])
    else
      @stock = Stock.find_by_ticker(params[:ticker])
      if @stock
        @stock = current_user.stocks.new(ticker: params[:ticker], name: params[:name], last_price: params[:last_price])
      else
        @stock = Stock.new_from_lookup(params[:ticker])
        if @stock.save
          @stock = current_user.stocks.new(ticker: params[:ticker], name: params[:name], last_price: params[:last_price])
        else
          @stock = nil
          flash[:error] = "Stock not available!"
        end
      end
    end
    respond_to do |format|
      if @stock.save
        format.html { redirect_to my_portfolio_path, notice: "Stock was successfully added" }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end

    end
  end

  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to my_portfolio_path, notice: 'Stock was successfully deleted.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:my_portfolio]

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def my_portfolio
  end

  def connect
    @friendships = current_user.friends
  end
# -----------------------------------------------------------
  def search
     @users = User.search(params[:search_param])
     respond_to do |format|
       if @users
         @users = current_user.execpt_current_user(@users)
         format.html { render partial: "friends/lookup" }
         format.json { render json: @users }
       else
         format.json { render status: :not_found, nothing: true }
       end
     end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      redirect_to connect_path, notice: "Friend was successfully added"
    else
      redirect_to connect_path
      flash[:error] = "Error adding friend"
    end
  end
# -----------------------------------------------------------
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render 'new'
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 spinner" style="display: none; text-align:center">
  <h5><i class="fa fa-circle-o-notch fa-spin fa-2x" aria-hidden="true"></i>Loading...</h5>
</div>

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3 style="text-align:center ">Search for Friends</h3>
  <%= form_tag get_friends_path, method: :get, id: 'friend-lookup-form' do |f| %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :search_param, params[:seach_param], placeholder: 'Name or Email...', autofocus: true, class: 'form-control search-box input-lg' %>
    </div>
    <div class="col-md-2">
      <%= submit_tag 'Search', class: "btn btn-lg btn-warning" %>
    </div>
  </div>
  <% end %>
  <%= render 'common/spinner'%>
    <% if @users %>
      <% if @users.count > 0%>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Email</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |friend| %>
            <tr>
              <th scope="row">1</th>
              <td><%= friend.name %></td>
              <td><%= friend.email %></td>
              <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary"%></td>
              <% if current_user.not_friends_with(friend.id)%>
                <td><%= link_to "Add Friend", create_friendship_path(user: current_user, friend: friend), class: "btn btn-success" %></td>
              <% else %>
                <td><%= "#{friend.name.capitalize}"%> already added</td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
    <div id="error-results"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StokApp2</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" media="screen" title="no title" charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if current_user %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Connect", connect_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Portfolio", my_portfolio_path%></li>
            </ul>
            <ul class="nav navbar-right">
              <li><%= link_to "Log out", logout_path %></li>
            </ul>
            <% else %>
            <ul class="nav navbar-right">
              <li><%= link_to "Log In", login_path%></li>
            </ul>
            <% end %>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search Friends...">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3 style="text-align:center ">Search for Stocks</h3>
  <%= form_tag get_stocks_path, method: :get, id: 'stock-lookup-form' do |f| %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :stock, params[:stock], placeholder: 'Stock Ticker Symbol', autofocus: true, class: 'form-control search-box input-lg' %>
    </div>
    <div class="col-md-2">
      <%= submit_tag 'Search', class: "btn btn-lg btn-warning" %>
    </div>
  </div>
  <% end %>
  <%= render 'common/spinner'%>
    <% if @tracker %>
      <div id="results" class="well">
        <strong>Price: </strong><%= @tracker.last_price %>
        <strong>Symbol: </strong><%= @tracker.ticker %>
        <strong>Name: </strong><%= @tracker.name %>
        <% if current_user.can_add?(@tracker.ticker)%>
          <%= link_to "Add Stock", create_stock_path(ticker: @tracker.ticker, name: @tracker.name, last_price: @tracker.last_price), class: "btn btn-success" %>
        <% else %>
          Stock Already added!
        <% end %>
      </div>
    <% end %>
    <div id="error-results"></div>
</div>


<div class="container-fluid" style="padding-top: 115px;">
  <% current_user.stocks.each do |stocks| %>
    <div id="already-added" class="row well">
      <div class="col-md-12">
        <strong>Price: </strong><%= stocks.last_price %>
        <strong>Symbol: </strong><%= stocks.ticker %>
        <strong>Name: </strong><%= stocks.name %>
        <%= link_to "Remove Stock", stocks, method: :delete, class: "btn btn-danger", id: "delete-stock" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/connect.html.erb
<h1>My Friends</h1>

<%= render 'friends/lookup'%>
<% if @friendships.count > 0%>
  <table class="table table-striped" id="friend-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
      <tr>
        <th scope="row">1</th>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
        <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary"%></td>
        <td><%= link_to "Unfriend", friendship_path(friend), method: :delete, class: "btn btn-danger", id: "delete-friend"%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row">
    <div class="col-lg-12">
      <p class="lead" style="text-align:center">
        No friends yet. Add some
      </p>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <br>
        <%= f.submit "Save changes", class: "btn btn-success" %>
      <% end %>
  </div>
</div>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

app/views/users/new.html.erb
<div class="sign-up container">
  <%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name%> </h1>
<% if current_user == @user %>
  <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-info", id: "edit-profile-button"%>
<% end %>
<div class="container-fluid">
<% if @user.stocks.count > 0%>
  <h3 style="margin: 0; padding-left: 13%; padding-bottom: 0.4%;">Added Stocks</h3>
  <div id="added" class="row well">
  <% @user.stocks.each do |stocks| %>
      <div class="col-md-12">
        <strong>Price: </strong><%= stocks.last_price %>
        <strong>Symbol: </strong><%= stocks.ticker %>
        <strong>Name: </strong><%= stocks.name %>
      </div>
  <% end %>
  </div>
<% else %>
  <p>
    No stocks being tracked
  </p>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Finance Tracker<% if current_user%> <%= current_user.name %> <% end %></h1>
<div class="container" id="stock_background">
  <% if current_user%>
  <h2 style="text-align:center; color:white;">Start to get a feel for the app!</h2>
    <div class="col-md-12" style="margin-left: 42%;">
      <%= link_to "Connect", connect_path, class: "btn btn-success" %> | <%= link_to "Stocks", get_stocks_path, class: "btn btn-warning"%>
    </div>
  <% else %>
  <h2 style="text-align:center; color:white;">Sign up! Track your stocks and other friends!</h2>
    <div class="col-md-12" style="margin-left: 42%;">
      <%= link_to "Sign Up", signup_path, class: "btn btn-success" %> | <%= link_to "Log In", login_path, class: "btn btn-info"%>
    </div>
  <% end %>
</div>